### ISSUE TITLE
使用 node 屡次碰壁，请教下

### ISSUE THREAD

**Issue by creazy412** [SirM2z/FT-seed#9]
`
> puppeteer@1.20.0 install /root/FT-seed/node_modules/puppeteer
> node install.js

ERROR: Failed to download Chromium r686378! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
{ Error: EACCES: permission denied, mkdir '/root/FT-seed/node_modules/puppeteer/.local-chromium'
  -- ASYNC --
    at BrowserFetcher.<anonymous> (/root/FT-seed/node_modules/puppeteer/lib/helper.js:111:15)
    at Object.<anonymous> (/root/FT-seed/node_modules/puppeteer/install.js:64:16)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/root/FT-seed/node_modules/puppeteer/.local- ' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer@1.20.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the puppeteer@1.20.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-01-23T15_23_55_179Z-debug.log
`
请教下，这是因为 chromium 未安装问题吗？

**Comment by yanwen** [comment]
@creazy412  这是网络不好。没下载  Chromium 。

解决方法是：挂代理 运行命令 下载下来就没问题了

**Comment by SirM2z** [comment]
> `
> 
> > puppeteer@1.20.0 install /root/FT-seed/node_modules/puppeteer
> 
> > node install.js
> 
> 
> 
> ERROR: Failed to download Chromium r686378! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
> 
> { Error: EACCES: permission denied, mkdir '/root/FT-seed/node_modules/puppeteer/.local-chromium'
> 
>   -- ASYNC --
> 
>     at BrowserFetcher.<anonymous> (/root/FT-seed/node_modules/puppeteer/lib/helper.js:111:15)
> 
>     at Object.<anonymous> (/root/FT-seed/node_modules/puppeteer/install.js:64:16)
> 
>     at Module._compile (internal/modules/cjs/loader.js:778:30)
> 
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
> 
>     at Module.load (internal/modules/cjs/loader.js:653:32)
> 
>     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
> 
>     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
> 
>     at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
> 
>     at startup (internal/bootstrap/node.js:283:19)
> 
>     at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
> 
>   errno: -13,
> 
>   code: 'EACCES',
> 
>   syscall: 'mkdir',
> 
>   path: '/root/FT-seed/node_modules/puppeteer/.local- ' }
> 
> npm ERR! code ELIFECYCLE
> 
> npm ERR! errno 1
> 
> npm ERR! puppeteer@1.20.0 install: `node install.js`
> 
> npm ERR! Exit status 1
> 
> npm ERR!
> 
> npm ERR! Failed at the puppeteer@1.20.0 install script.
> 
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> 
> 
> npm ERR! A complete log of this run can be found in:
> 
> npm ERR!     /root/.npm/_logs/2021-01-23T15_23_55_179Z-debug.log
> 
> `
> 
> 请教下，这是因为 chromium 未安装问题吗？

权限的问题 sudo 试一下

**Comment by creazy412** [comment]
chromium 不支持在树莓派上【我的是3B+】安装，填了好久的坑，才发现的；最后在电脑的虚拟机里面安装成功了

**Comment by wugh888** [comment]
npm install puppeteer --unsafe-perm
